spring.application.name=MovieTicketBookRealProject

spring.datasource.url=jdbc:mysql://localhost:3306/moviebookingapp
spring.datasource.username=root
spring.datasource.password=Root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

jwt.secretKey=b779d5b80e6a8bd2e6ba1cc9310018be
jwt.expiration=3600000
